import pic15 from "../assets/Poster/pic15.jpg";

export const Data = [
  {
    id: 1,
    title: "Ballerina",
    releaseDate: "12 Jun 2025",
    duration: "2h 4min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/Movies/HO00001917",
    genre: "Action",
    overview:
      "An assassin trained in the traditions of the Ruska Roma organization sets out to seek revenge after her father's death.",
    rating: 8.3,
    director: "",
    cast: "",
    language: "English",
  },
  {
    id: 2,
    title: "Guardian, The",
    releaseDate: "12 Jun 2025",
    duration: "1h 15min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/Movies/HO00001902",
    genre: "Horror",
    overview: "NA",
    rating: 7.5,
    director: "",
    cast: "",
    language: "English",
  },
  {
    id: 3,
    title: "How to Train Your Dragon",
    releaseDate: "12 Jun 2025",
    duration: "2h 5min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/Movies/HO00001923",
    genre: "Adventure",
    overview:
      "As an ancient threat endangers both Vikings and dragons alike on the isle of Berk, the friendship between Hiccup and Toothless becomes the key to forging a new future together.",
    rating: 9.0,
    director: "",
    cast: "",
    language: "English",
  },
  {
    id: 4,
    title: "In Love With My Bestfriend",
    releaseDate: "11 Jun 2025",
    duration: "1h 45min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/Movies/HO00001939",
    genre: "Romance",
    overview:
      "A remake of Thailand's 'Friendzone', focusing on the ironic love story between two best friends of the opposite sex who always miss the chance to be together.",
    rating: 7.8,
    director: "",
    cast: "",
    language: "Khmer",
  },
  {
    id: 5,
    title: "It Feeds",
    releaseDate: "09 Jun 2025",
    duration: "1h 42min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/Movies/HO00001921",
    genre: "Horror",
    overview:
      "After a young girl bursts into their home psychiatry practice claiming an entity is feeding on her, Jordan and her clairvoyant mother must stop the force before the girl is taken completely.",
    rating: 7.6,
    director: "",
    cast: "",
    language: "English",
  },
  {
    id: 6,
    title: "Hi-Five",
    releaseDate: "06 Jun 2025",
    duration: "2h 0min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/Movies/HO00001938",
    genre: "Action",
    overview:
      "Five ordinary people who gained superpowers through organ transplants from a superpowered being must fight a psychic villain who covets their powers.",
    rating: 8.2,
    director: "",
    cast: "",
    language: "Korean",
  },
  {
    id: 7,
    title: "Setan Botak Di Jembatan Ancol",
    releaseDate: "06 Jun 2025",
    duration: "1h 19min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/Movies/HO00001970",
    genre: "Horror",
    overview:
      "After her adopted sister's death, Nirmala is haunted by a figure in red. Meanwhile, the Bald Devil returns for revenge and dark secrets unravel in a terrifying battle for survival.",
    rating: 7.4,
    director: "",
    cast: "",
    language: "Indonesian",
  },
  {
    id: 8,
    title: "Karate Kid: Legends",
    releaseDate: "05 Jun 2025",
    duration: "1h 34min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/Movies/HO00001632",
    genre: "Action",
    overview:
      "After moving to New York, kung fu prodigy Li Fong must combine his past and new teachings to compete in a karate tournament and help a friend in need.",
    rating: 7.9,
    director: "",
    cast: "",
    language: "English",
  },
  {
    id: 9,
    title: "Mae Neath",
    releaseDate: "05 Jun 2025",
    duration: "1h 45min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/Movies/HO00001901",
    genre: "Horror",
    overview: "NA",
    rating: 7.3,
    director: "",
    cast: "",
    language: "Khmer",
  },
  {
    id: 10,
    title: "Lilo & Stitch",
    releaseDate: "23 May 2025",
    duration: "1h 48min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/Movies/HO00001853",
    genre: "Action",
    overview:
      "Live-action remake of Disney's animated classic 'Lilo and Stitch'.",
    rating: 8.5,
    director: "",
    cast: "",
    language: "English",
  },
  {
    id: 11,
    title: "Mission: Impossible - The Final Reckoning",
    releaseDate: "22 May 2025",
    duration: "2h 49min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/Movies/HO00001897",
    genre: "Action",
    overview:
      "Our lives are the sum of our choices. Tom Cruise returns as Ethan Hunt in the final chapter of the Mission: Impossible saga.",
    rating: 9.3,
    director: "",
    cast: "Tom Cruise",
    language: "English",
  },
  {
    id: 12,
    title: "Holy Night: Demon Hunters",
    releaseDate: "15 May 2025",
    duration: "1h 32min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/Movies/HO00001851",
    genre: "Action",
    overview:
      "An occult action film in which a team of demon hunters fights against evil spirits to protect humanity from dark forces.",
    rating: 7.7,
    director: "",
    cast: "",
    language: "Korean",
  },
];

export const Info = [
  { image: pic15 },
];
