import pic15 from "../assets/Poster/pic15.jpg";

export const currentShow = [
  {
    id: 1,
    title: "Ballerina",
    releaseDate: "12 Jun 2025",
    duration: "2h 4min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/Movies/HO00001917",
    genre: "Action",
    overview:
      "An assassin trained in the traditions of the Ruska Roma organization sets out to seek revenge after her father's death.",
    rating: 8.3,
    director: "",
    cast: "",
    language: "English",
  },
  {
    id: 2,
    title: "Guardian, The",
    releaseDate: "12 Jun 2025",
    duration: "1h 15min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/Movies/HO00001902",
    genre: "Horror",
    overview: "NA",
    rating: 7.5,
    director: "",
    cast: "",
    language: "English",
  },
  {
    id: 3,
    title: "How to Train Your Dragon",
    releaseDate: "12 Jun 2025",
    duration: "2h 5min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/Movies/HO00001923",
    genre: "Adventure",
    overview:
      "As an ancient threat endangers both Vikings and dragons alike on the isle of Berk, the friendship between Hiccup and Toothless becomes the key to forging a new future together.",
    rating: 9.0,
    director: "",
    cast: "",
    language: "English",
  },
  {
    id: 4,
    title: "In Love With My Bestfriend",
    releaseDate: "11 Jun 2025",
    duration: "1h 45min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/Movies/HO00001939",
    genre: "Romance",
    overview:
      "A remake of Thailand's 'Friendzone', focusing on the ironic love story between two best friends of the opposite sex who always miss the chance to be together.",
    rating: 7.8,
    director: "",
    cast: "",
    language: "Khmer",
  },
  {
    id: 5,
    title: "It Feeds",
    releaseDate: "09 Jun 2025",
    duration: "1h 42min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/Movies/HO00001921",
    genre: "Horror",
    overview:
      "After a young girl bursts into their home psychiatry practice claiming an entity is feeding on her, Jordan and her clairvoyant mother must stop the force before the girl is taken completely.",
    rating: 7.6,
    director: "",
    cast: "",
    language: "English",
  },
  {
    id: 6,
    title: "Hi-Five",
    releaseDate: "06 Jun 2025",
    duration: "2h 0min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/Movies/HO00001938",
    genre: "Action",
    overview:
      "Five ordinary people who gained superpowers through organ transplants from a superpowered being must fight a psychic villain who covets their powers.",
    rating: 8.2,
    director: "",
    cast: "",
    language: "Korean",
  },
  {
    id: 7,
    title: "Setan Botak Di Jembatan Ancol",
    releaseDate: "06 Jun 2025",
    duration: "1h 19min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/Movies/HO00001970",
    genre: "Horror",
    overview:
      "After her adopted sister's death, Nirmala is haunted by a figure in red. Meanwhile, the Bald Devil returns for revenge and dark secrets unravel in a terrifying battle for survival.",
    rating: 7.4,
    director: "",
    cast: "",
    language: "Indonesian",
  },
  {
    id: 8,
    title: "Karate Kid: Legends",
    releaseDate: "05 Jun 2025",
    duration: "1h 34min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/Movies/HO00001632",
    genre: "Action",
    overview:
      "After moving to New York, kung fu prodigy Li Fong must combine his past and new teachings to compete in a karate tournament and help a friend in need.",
    rating: 7.9,
    director: "",
    cast: "",
    language: "English",
  },
  {
    id: 9,
    title: "Mae Neath",
    releaseDate: "05 Jun 2025",
    duration: "1h 45min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/Movies/HO00001901",
    genre: "Horror",
    overview: "NA",
    rating: 7.3,
    director: "",
    cast: "",
    language: "Khmer",
  },
  {
    id: 10,
    title: "Lilo & Stitch",
    releaseDate: "23 May 2025",
    duration: "1h 48min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/Movies/HO00001853",
    genre: "Action",
    overview:
      "Live-action remake of Disney's animated classic 'Lilo and Stitch'.",
    rating: 8.5,
    director: "",
    cast: "",
    language: "English",
  },
  {
    id: 11,
    title: "Mission: Impossible - The Final Reckoning",
    releaseDate: "22 May 2025",
    duration: "2h 49min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/Movies/HO00001897",
    genre: "Action",
    overview:
      "Our lives are the sum of our choices. Tom Cruise returns as Ethan Hunt in the final chapter of the Mission: Impossible saga.",
    rating: 9.3,
    director: "",
    cast: "Tom Cruise",
    language: "English",
  },
  {
    id: 12,
    title: "Holy Night: Demon Hunters",
    releaseDate: "15 May 2025",
    duration: "1h 32min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/Movies/HO00001851",
    genre: "Action",
    overview:
      "An occult action film in which a team of demon hunters fights against evil spirits to protect humanity from dark forces.",
    rating: 7.7,
    director: "",
    cast: "",
    language: "Korean",
  },
];


export const upcomingShow = [
  {
    id: 1,
    title: "Witch Returns, The",
    releaseDate: "18 Jun 2025",
    duration: "1h 30min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/FilmPosterGraphic/HO00001903",
    genre: "Horror",
    overview:
      "NA",
    rating: 8.3,
    director: "",
    cast: "",
    language: "English",
  },
  {
    id: 2,
    title: "Elio",
    releaseDate: "19 Jun 2025",
    duration: "1h 38min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/FilmPosterGraphic/HO00001854",
    genre: "Animation",
    overview: "Elio, a space fanatic with an active imagination, finds himself on a cosmic misadventure where he must form new bonds with alien lifeforms, navigate a crisis of intergalactic proportions and somehow discover who he is truly meant to be.",
    rating: 7.5,
    director: "",
    cast: "",
    language: "English",
  },
  {
    id: 3,
    title: "28 Years Later",
    releaseDate: "19 Jun 2025",
    duration: "1h 55min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/FilmPosterGraphic/HO00001855",
    genre: "Horror",
    overview:
      "A group of survivors of the rage virus lives on a small island. When one of the group leaves the island on a mission into the mainland, he discovers secrets, wonders, and horrors that have mutated not only the infected but other survivors.",
    rating: 9.0,
    director: "",
    cast: "",
    language: "English",
  },
  {
    id: 4,
    title: "Pernikahan Arwah",
    releaseDate: "20 Jun 2025",
    duration: "1h 41min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/FilmPosterGraphic/HO00001959",
    genre: "Horror",
    overview:
      "A couple, Salim and Tasya, who are preparing for their wedding. However, their happy plans are disrupted when Salim's aunt, his only blood relative, dies.",
    rating: 7.8,
    director: "",
    cast: "",
    language: "Khmer",
  },
  {
    id: 5,
    title: "Dendam Malam Kelam",
    releaseDate: "23 Jun 2025",
    duration: "1h 44min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/FilmPosterGraphic/HO00001940",
    genre: "Horror",
    overview:
      "Jefri and Sarah, a couple who are having an affair. The two of them have to desperately create an alibi after Sofia, Jefri's legal wife, is killed and her body disappears.",
    rating: 7.6,
    director: "",
    cast: "",
    language: "English",
  },
  {
    id: 6,
    title: "Lovesick",
    releaseDate: "25 Jun 2025",
    duration: "1h 51min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/FilmPosterGraphic/HO00001971",
    genre: "Romance",
    overview:
      "In order to avoid being expelled from school, Ye Zi Jie lied and pretended to be sick. He used all kinds of tricks, including putting panda make-up to pretend to look pale, riding his bike into a fence, or even telling his teacher he was not fine to order to sleep at the school health room. Unexpectedly, the teacher sent Ye Zi, the class monitor who has the same name as him, to show special concern. She always has evidence about his fake illness, and she follows closely just to confirm whether he is really sick or not. Gradually, the two get to know each other better in the spy-to-spy interaction, and become closer and closer...",
    rating: 8.2,
    director: "",
    cast: "",
    language: "Korean",
  },
  {
    id: 7,
    title: "Hand, The",
    releaseDate: "26 Jun 2025",
    duration: "1h 33min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/FilmPosterGraphic/HO00001957",
    genre: "Horror",
    overview:
      "NA",
    rating: 7.4,
    director: "",
    cast: "",
    language: "Khmer",
  },
  {
    id: 8,
    title: "F1",
    releaseDate: "26 Jun 2025",
    duration: "2h 35min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/FilmPosterGraphic/HO00001856",
    genre: "Drama",
    overview:
      "Follows a Formula One driver who comes out of retirement to mentor and team with a younger driver.",
    rating: 7.9,
    director: "",
    cast: "",
    language: "English",
  },
  {
    id: 9,
    title: "Pembantaian Dukun Santet",
    releaseDate: "27 Jun 2025",
    duration: "1h 32min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/FilmPosterGraphic/HO00001976",
    genre: "Horror",
    overview: "A community conflict occurred, those accused of being witch doctors were killed without having the chance to defend themselves. Chaos was everywhere.",
    rating: 7.3,
    director: "",
    cast: "",
    language: "Indo",
  },
  {
    id: 10,
    title: "M3GAN 2.0",
    releaseDate: "27 Jun 2025",
    duration: "2h 0min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/FilmPosterGraphic/HO00001941",
    genre: "Horror",
    overview:
      "Two years after M3GAN's rampage, her creator, Gemma, resorts to resurrecting her infamous creation in order to take down Amelia, the military-grade weapon who was built by a defense contractor who stole M3GAN's underlying tech.",
    rating: 8.5,
    director: "",
    cast: "",
    language: "English",
  },
  {
    id: 11,
    title: "Ritual, The",
    releaseDate: "30 Jun 2025",
    duration: "1h 47min",
    image: "https://tickets.legend.com.kh/CDN/media/entity/get/FilmPosterGraphic/HO00001922",
    genre: "Horror",
    overview:
      "Two priests, one in crisis with his faith and the other confronting a turbulent past, must overcome their differences to perform a risky exorcism.",
    rating: 9.3,
    director: "",
    cast: "Tom Cruise",
    language: "English"
  },
]

export const Info = [
  { image: pic15 },
];
